VahinShop2/vahinshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),
     path('about', views.about, name='about')
]

VahinShop2/vahinshop/users/urls.py
from django.urls import path
from users import views as userViews
from django.contrib.auth import views as authViews
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login

app_name = 'users'

urlpatterns = [
    path('registration/', userViews.register, name="reg"),
    path('login/', authViews.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('exit/', authViews.LogoutView.as_view(template_name='shop/product/list.html'), name="exit"),

]

VahinShop2/vahinshop/vahinshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VahinShop2/vahinshop/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='static/img/products/%Y', blank=False)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

VahinShop2/vahinshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

def about(request):
    return render(request, 'shop/product/about.html')

VahinShop2/vahinshop/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Vahin-shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Oswald:wght@200;300;400;500;600;700&display=swap"
        rel="stylesheet">
    <link href="{% static 'css/main.css' %}" type='text/css' rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>

    <header>
        <div class="header">
            <ul class="header_list_container">
                <li><a class="header_list_button" href="{% url 'shop:about' %}">Оплата|Доставка|Контакты</a></li>
            </ul>
            <a href="{% url 'shop:product_list' %}" class="header_logo">
                <img src="../../../static/img/Logo.jpg" alt="Логотип сайта" width="240" height="60">
            </a>
            <ul class="header_cabinet_container">
                {% if user.is_authenticated %}
                <li><a class="header_list_button" href="{% url 'users:reg' %}">Личный кабинет</a></li>
                <li><a class="header_list_button" href="{% url 'users:exit' %}">Выход</a></li>
                {% else %}
                <li><a class="header_list_button" href="{% url 'users:reg' %}">Регистрация</a></li>
                <li><a class="header_list_button" href="{% url 'users:login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
    </header>

    <!-- {% block slider_container %}slider_container{% endblock %} -->

    {% block content %}content{% endblock %}

    <div class="footer">
        <div class="footer_container">
            <div class="footer_contact">
                <a href="mailto:i.voxin@yandex.ru">Почта для связи: тык</a>
                <a href="tg://resolve?domain=vahin_shop">Телеграм: тык</a>
            </div>
            <div class="footer_law">
                <p>Вся представленная продукция сувенирная и не является игрушкой! © ИП Вахин (16+) (2023)</p>
            </div>
        </div>
    </div>

    <script defer src="{% static 'js/counter.js' %}"></script>
    <script defer src="{% static 'js/main.js' %}"></script>
</body>