VahinShop2/vahinshop/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

VahinShop2/vahinshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),
     path('about', views.about, name='about')
]

VahinShop2/vahinshop/vahinshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VahinShop2/vahinshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

VahinShop2/vahinshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product
from django.http import JsonResponse

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    # return JsonResponse({})
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

VahinShop2/vahinshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Корзина
{% endblock %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>Изображение</th>
            <th>Название</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Стоимость одного товара</th>
            <th>Стоимость всех товаров</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}"><img
                        src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/img_null.png' %}{% endif %}"
                        alt="Изображение товара">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <button type="submit">Обновить</button>
                    {% csrf_token %}
                </form>
            </td>
            <td class="push"><a href="{% url 'cart:cart_remove' product.id%}">Удалить</a></td>
            <td>{{ item.price }}₽</td>
            <td>{{ item.total_price }}₽</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr>
            <td colspan="4"></td>
            <td>Общая стоимость корзины</td>
            <td>{{ cart.get_total_price }}₽</td>
        </tr>
        <tr>
            <td class="push"><a href="{% url 'shop:product_list' %}" class="button light">Вернуться в магазин</a></td>
            <td colspan="4"></td>
            <td class="push"><a href="{% url 'orders:order_create' %}" class="button">Оформить заказ</a></td>
        </tr>
    </tbody>
</table>
{% endblock %}